add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "\\$"
error_symbol = "\\$"

[cmd_duration]
disabled = true

[aws]
symbol = " "
format = "[$symbol]($style)"

[conda]
symbol = " "
format = "[$symbol]($style)"

[dart]
symbol = " "
format = "[$symbol]($style)"

[directory]
read_only = " "

[docker]
symbol = " "
format = "[$symbol]($style)"

[elixir]
symbol = " "
format = "[$symbol]($style)"

[elm]
symbol = " "
format = "[$symbol]($style)"

[git_branch]
symbol = " "

[golang]
symbol = " "
format = "[$symbol]($style)"

[haskell]
symbol = " "
format = "[$symbol]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "[$symbol]($style)"

[julia]
symbol = " "
format = "[$symbol]($style)"

[memory_usage]
symbol = " "
format = "[$symbol]($style)"

[nim]
symbol = " "
format = "[$symbol]($style)"

[nix_shell]
symbol = " "
format = "[$symbol]($style)"

[nodejs]
symbol = " "
format = "[$symbol]($style)"

[package]
symbol = " "
format = "[$symbol]($style)"

[perl]
symbol = " "
format = "[$symbol]($style)"

[php]
symbol = " "
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[$symbol]($style)"

[ruby]
symbol = " "
format = "[$symbol]($style)"

[rust]
symbol = " "
format = "[$symbol]($style)"

[swift]
symbol = "ﯣ "
format = "[$symbol]($style)"
